import { vaultlist } from "../vaultlist";

export const daiyvaultfuncs = [
    {   ...vaultlist["DAIyVault"],
        functionName: 'name'},
    {   ...vaultlist["DAIyVault"],
        functionName: 'symbol'},
    {   ...vaultlist["DAIyVault"],
        functionName: 'totalSupply'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'totalAssets'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'maxAvailableShares'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'pricePerShare'},
    // {   ...vaultlist["DAIyVault"],
    // functionName: 'debtOutstanding'},
    // {   ...vaultlist["DAIyVault"],
    // functionName: 'creditAvailable'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'availableDepositLimit'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'depositLimit'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'totalDebt'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'lockedProfit'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'debtRatio'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'lastReport'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'activation'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'lockedProfitDegradation'},
    {   ...vaultlist["DAIyVault"],
    functionName: 'performanceFee'}
    ]